name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/pluggedcomputing/pixel-plugged-computing-web-front:latest
        cache-from: type=registry,ref=ghcr.io/pluggedcomputing/pixel-plugged-computing-web-front:latest
        cache-to: type=inline

    - name: Callback portainer webhook
      uses: muinmomin/webhook-action@v1.0.0
      with:
        url: ${{ secrets.PORTAINER_WEBHOOK }}
